services:
  # Banco de Dados para Desenvolvimento
  db_dev:
    image: postgres:14
    container_name: podo_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: 
      - "postgres"
      - "-c"
      - "shared_buffers=2GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "statement_timeout=0"
    ports:
      - "5432:5432"
   
  app:
    build: .
    container_name: podo_app
    command: ${APP_COMMAND}  
    restart: always
    volumes:
      - .:/app
      - ./media:/app/media  # Mapeia o diretório media local para o contêiner
    ports:
      - "8000:8000"
    depends_on:
      - db_dev
    env_file:
      - .env

volumes:
  postgres_data_dev:
  