# Generated by Django 5.2.6 on 2025-09-29 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_alter_patient_phone_1_alter_patient_phone_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do procedimento realizado', max_length=100)),
                ('procedure_date', models.DateField(help_text='Data em que o procedimento foi realizado')),
                ('notes', models.TextField(blank=True, help_text='Observações adicionais sobre o procedimento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Paciente relacionado ao procedimento', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['-procedure_date'],
            },
        ),
    ]
