# Generated by Django 5.2.6 on 2025-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Primeiro nome do paciente', max_length=30)),
                ('last_name', models.CharField(help_text='Sobrenome do paciente', max_length=30)),
                ('date_of_birth', models.DateField(help_text='Data de nascimento do paciente')),
                ('medical_record_number', models.CharField(help_text='Número do prontuário médico', max_length=20, unique=True)),
            ],
        ),
    ]
