# Generated by Django 5.2.6 on 2025-09-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o paciente está ativo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_schedule_date',
            field=models.DateField(blank=True, help_text='Data do último agendamento do paciente', null=True),
        ),
    ]
