# Generated by Django 5.2.6 on 2025-09-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_is_active_patient_last_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text='Endereço de e-mail do paciente', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', help_text='Gênero do paciente', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_1',
            field=models.CharField(blank=True, help_text='Número de telefone principal do paciente', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_2',
            field=models.CharField(blank=True, help_text='Número de telefone secundário do paciente', max_length=15, null=True),
        ),
    ]
