# Generated by Django 5.2.6 on 2025-09-29 16:36

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_email_patient_gender_patient_phone_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Número de telefone principal do paciente', max_length=15, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Número de telefone secundário do paciente', max_length=15, null=True, region=None),
        ),
    ]
